Далее посчитаем метрики - основные показатели по данному датасету

In [1]:
import pandas as pd 
df=pd.read_csv('/Users/denis/Programming/DA/customer_churn_eda/data/processed/churn_clean.csv')

Проверим количество пользователей, которые отказались от покупки

In [5]:
churn_rate=df['churn_flag'].mean()
print(f'Churn rate: {churn_rate:.1%}')

Churn rate: 26.6%

In [6]:
contract_metrics = (df.groupby('Contract')
    .agg(customers=('customerID','count'), churn_rate=('churn_flag','mean'), avg_monthly=('MonthlyCharges','mean'))
    .sort_values('churn_rate', ascending=False))
contract_metrics

                customers  churn_rate  avg_monthly
Contract
Month-to-month       3875    0.427097    66.398490
One year             1472    0.112772    65.079416
Two year             1685    0.028487    60.872374

In [7]:
bins=[0,6,12,24,48,100]
labels=['0-6','7-12','13-24','25-48','49+']
df['tenure_group']=pd.cut(df['tenure'],bins=bins,labels=labels,include_lowest=True)
df.groupby('tenure_group')['churn_flag'].agg(['count','mean'])

              count      mean
tenure_group
0-6            1470  0.533333
7-12            705  0.358865
13-24          1024  0.287109
25-48          1594  0.203890
49+            2239  0.095132

In [12]:
df.groupby('PaymentMethod')['churn_flag'].mean().to_frame()

                           churn_flag
PaymentMethod
Bank transfer (automatic)    0.167315
Credit card (automatic)      0.152531
Electronic check             0.452854
Mailed check                 0.192020

In [13]:
df.groupby('InternetService')['churn_flag'].mean().to_frame()

                 churn_flag
InternetService
DSL                0.189983
Fiber optic        0.418928
No                 0.074342